run:
  deadline: 5m
  skip-dirs:
    - internal/go

linters:
  enable:
    - depguard
    - godot
    - gofumpt
    - goimports
    - revive
    - whitespace

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - sync/atomic: "Use go.uber.org/atomic instead of sync/atomic"
      - debug/elf: "Use github.com/parca-dev/parca/internal/go/debug/elf instead of debug/elf"
      - github.com/stretchr/testify/assert: "Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert"
      - github.com/go-kit/kit/log: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
      - github.com/pkg/errors: "Use fmt.Errorf instead"
  errcheck:
    exclude: ./.errcheck_excludes.txt
  goimports:
    local-prefixes: github.com/parca-dev/parca
  gofumpt:
    extra-rules: true
  misspell:
    locale: US
