apiVersion: apps/v1
kind: Deployment
metadata:
  name: promcheck-exporter
  namespace: monitoring
  labels:
    app: promcheck-exporter
spec:
  replicas: 1
  template:
    metadata:
      name: promcheck-exporter
      labels:
        app: promcheck-exporter
    spec:
      containers:
        - name: promcheck-exporter
          image: ghcr.io/cbrgm/promcheck:latest
          imagePullPolicy: Always
          ports:
            - name: internal
              containerPort: 9212
          args:
            - "--prometheus.url=http://0.0.0.0:9093" # change me to my cluster dns name
            - "--exporter.enabled=true"
            - "--exporter.addr=0.0.0.0:9212"
            - "--exporter.interval=300"
            - "--log.level=info"
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: promcheck-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: promcheck-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9212'
spec:
  selector:
    app: promcheck-exporter
  type: ClusterIP
  ports:
    - port: 9212
      targetPort: 9212
