---
name: automerge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:

      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Approve request
        id: approve
        run: gh pr review --approve ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Enable automerge
        id: automerge
        run: gh pr merge --rebase --auto ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'

    steps:
      - name: Approve request
        id: approve
        run: gh pr review --approve ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Enable automerge
        id: automerge
        run: gh pr merge --rebase --auto ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}

  cbrgm:
    runs-on: ubuntu-latest
    if: github.actor == 'cbrgm' && contains(github.event.pull_request.labels.*.name, 'auto-merge')

    steps:
      - name: Enable automerge
        id: automerge
        run: gh pr merge --rebase --auto ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}
...
