on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: test-and-build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'

      - name: get modules
        run: go mod vendor

      - name: test
        run: make test

      - name: build
        run: make build
