on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: test-and-build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Get modules
        run: go mod vendor
      - name: Test
        run: make test
      - name: Build
        run: make build
