name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set release env
        run: echo "release_version=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'
      - name: Get modules
        run: go mod vendor
      - name: Test
        run: make test
      - name: Build
        run: make release
      - name: Package
        run: |
          rsync ./bin/promcheck_darwin_amd64 README.md LICENSE promcheck_darwin_amd64 && tar czvf promcheck_darwin_amd64.tar.gz promcheck_darwin_amd64
          rsync ./bin/promcheck_darwin_arm64 README.md LICENSE promcheck_darwin_arm64 && tar czvf promcheck_darwin_arm64.tar.gz promcheck_darwin_arm64
          rsync ./bin/promcheck_linux_amd64 README.md LICENSE promcheck_linux_amd64 && tar czvf promcheck_linux_amd64.tar.gz promcheck_linux_amd64
          rsync ./bin/promcheck_linux_arm64 README.md LICENSE promcheck_linux_arm64 && tar czvf promcheck_linux_arm64.tar.gz promcheck_linux_arm64
          rsync ./bin/promcheck_windows_amd64 README.md LICENSE promcheck_windows_amd64 && tar czvf promcheck_windows_amd64.tar.gz promcheck_windows_amd64
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            promcheck_darwin_amd64.tar.gz
            promcheck_darwin_arm64.tar.gz
            promcheck_linux_amd64.tar.gz
            promcheck_linux_arm64.tar.gz
            promcheck_windows_amd64.tar.gz
